"""add memory lifecycle fields

Revision ID: 003_memory_lifecycle
Revises: '002_add_core_tables'
Create Date: 2026-08-02 08:48:41.670578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003_memory_lifecycle'
down_revision: Union[str, None] = '002_add_core_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to add server
    # defaults so this is safe to run against a table that already has rows
    # (SQLite/most DBs reject a NOT NULL column add without one) ###
    op.add_column('memories', sa.Column('confidence', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('memories', sa.Column('last_used', sa.DateTime(), nullable=True))
    op.add_column('memories', sa.Column('access_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('memories', sa.Column('verification_state', sa.String(), nullable=False, server_default='unverified'))
    op.create_index(op.f('ix_memories_last_used'), 'memories', ['last_used'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_last_used'), table_name='memories')
    op.drop_column('memories', 'verification_state')
    op.drop_column('memories', 'access_count')
    op.drop_column('memories', 'last_used')
    op.drop_column('memories', 'confidence')
    # ### end Alembic commands ###
